openapi: 3.0.0
info:
  title: my authentication API for test projects
  description: A simple API
  version: 0.0.1
servers:
- url: /
paths:
  /register:
    post:
      summary: Register a new user
      description: This endpoint allows users to register by providing basic information.
      operationId: registerPOST
      requestBody:
        description: User registration data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/register_body'
        required: true
      responses:
        "201":
          description: User successfully registered
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_201'
        "400":
          description: Bad request (e.g. missing parameters)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_400'
      x-swagger-router-controller: Default
  /login:
    post:
      summary: Log in a user
      description: "This endpoint allows users to log in by providing their username\
        \ and password. If the credentials are valid, a JWT token will be returned."
      operationId: loginPOST
      requestBody:
        description: User login credentials
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/login_body'
        required: true
      responses:
        "200":
          description: "Successful login, JWT token returned"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
        "401":
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_401'
      x-swagger-router-controller: Default
components:
  schemas:
    register_body:
      required:
      - email
      - password
      - username
      type: object
      properties:
        username:
          type: string
          example: johndoe
        password:
          type: string
          format: password
          example: P@ssw0rd
        email:
          type: string
          format: email
          example: johndoe@example.com
    inline_response_201:
      type: object
      properties:
        message:
          type: string
          example: User registered successfully
      example:
        message: User registered successfully
    inline_response_400:
      type: object
      properties:
        error:
          type: string
          example: Invalid request data
    login_body:
      required:
      - password
      - username
      type: object
      properties:
        username:
          type: string
          example: johndoe
        password:
          type: string
          format: password
          example: P@ssw0rd
    inline_response_200:
      type: object
      properties:
        token:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
      example:
        token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
    inline_response_401:
      type: object
      properties:
        error:
          type: string
          example: Invalid username or password
